service: serverless-rds-service

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  iam:
    role: arn:aws:iam::003178017432:role/RDSRole

functions:
  serverWithDatabase:
    handler: dist/main.handler
    events:
      - http:
          method: any
          path: /{any+}
